package net.mcreator.jojohe.configuration;

import net.minecraftforge.common.ForgeConfigSpec;

public class JoJoHEHamonConfiguration {
	public static final ForgeConfigSpec.Builder BUILDER = new ForgeConfigSpec.Builder();
	public static final ForgeConfigSpec SPEC;
	public static final ForgeConfigSpec.ConfigValue<Double> HAMONDMGMULT;
	public static final ForgeConfigSpec.ConfigValue<Double> HAMONBARMIN;
	public static final ForgeConfigSpec.ConfigValue<Double> HAMONBARMAX;
	public static final ForgeConfigSpec.ConfigValue<Double> HERMITMAXATK;
	public static final ForgeConfigSpec.ConfigValue<Double> HERMITMAXHEALTH;
	public static final ForgeConfigSpec.ConfigValue<Double> HERMITMAXSPEED;
	public static final ForgeConfigSpec.ConfigValue<Boolean> WARRIORENABLED;
	public static final ForgeConfigSpec.ConfigValue<Double> WARRIORMAXATK;
	public static final ForgeConfigSpec.ConfigValue<Double> WARRIORMAXHEALTH;
	public static final ForgeConfigSpec.ConfigValue<Double> WARRIORMAXSPEED;
	public static final ForgeConfigSpec.ConfigValue<Boolean> WISDOMENABLEDATK;
	public static final ForgeConfigSpec.ConfigValue<Double> WISDOMMAX;
	public static final ForgeConfigSpec.ConfigValue<Double> WISDOMMAXHEALTH;
	public static final ForgeConfigSpec.ConfigValue<Double> WISDOMMAXSPEED;
	public static final ForgeConfigSpec.ConfigValue<Boolean> DEFENDERENABLED;
	public static final ForgeConfigSpec.ConfigValue<Double> DEFENDERMAXATK;
	public static final ForgeConfigSpec.ConfigValue<Double> DEFENDERMAXHEALTH;
	public static final ForgeConfigSpec.ConfigValue<Double> DEFENDERMAXSPEED;
	public static final ForgeConfigSpec.ConfigValue<Boolean> ENVIOUSENABLED;
	public static final ForgeConfigSpec.ConfigValue<Double> ENVIOUSMAXATK;
	public static final ForgeConfigSpec.ConfigValue<Double> ENVIOUSMAXHEALTH;
	public static final ForgeConfigSpec.ConfigValue<Double> ENVIOUSMAXSPEED;
	public static final ForgeConfigSpec.ConfigValue<Boolean> TRICKSTERENABLED;
	public static final ForgeConfigSpec.ConfigValue<Double> TRICKSTERMAXATK;
	public static final ForgeConfigSpec.ConfigValue<Double> TRICKSTERMAXHEALTH;
	public static final ForgeConfigSpec.ConfigValue<Double> TRICKSTERMAXSPEED;
	public static final ForgeConfigSpec.ConfigValue<Boolean> BUBBLYENABLED;
	public static final ForgeConfigSpec.ConfigValue<Double> BUBBLYMAXATK;
	public static final ForgeConfigSpec.ConfigValue<Double> BUBBLYMAXHEALTH;
	public static final ForgeConfigSpec.ConfigValue<Double> BUBBLYMAXSPEED;
	public static final ForgeConfigSpec.ConfigValue<Boolean> STYLISHENABLED;
	public static final ForgeConfigSpec.ConfigValue<Double> STYLISHMAXATK;
	public static final ForgeConfigSpec.ConfigValue<Double> STYLISHMAXHEALTH;
	public static final ForgeConfigSpec.ConfigValue<Double> STYLISHMAXSPEED;
	static {
		BUILDER.push("Hamon Basics");
		HAMONDMGMULT = BUILDER.comment("Multiplier for Hamon damage against Vampires").define("Hamon Damage Multiplier", (double) 1);
		HAMONBARMIN = BUILDER.comment("Amount of Hamon at No Mastery").define("Hamon Bar Min", (double) 5);
		HAMONBARMAX = BUILDER.comment("Amount of Hamon at Max Mastery").define("Hamon Bar Max", (double) 10);
		BUILDER.pop();
		BUILDER.push("Hamon Root: Hermit");
		HERMITMAXATK = BUILDER.define("Hermit Max Attack", (double) 0);
		HERMITMAXHEALTH = BUILDER.define("Hermit Max Health", (double) 0);
		HERMITMAXSPEED = BUILDER.define("Hermit Max Speed", (double) 0);
		BUILDER.pop();
		BUILDER.push("Hamon Root: Warrior");
		WARRIORENABLED = BUILDER.define("Warrior Enabled", true);
		WARRIORMAXATK = BUILDER.define("Warrior Max Attack", (double) 0);
		WARRIORMAXHEALTH = BUILDER.define("Warrior Max Health", (double) 0);
		WARRIORMAXSPEED = BUILDER.define("Warrior Max Speed", (double) 0);
		BUILDER.pop();
		BUILDER.push("Hamon Root: Wisdom");
		WISDOMENABLEDATK = BUILDER.define("Wisdom Enabled", true);
		WISDOMMAX = BUILDER.define("Wisdom Max Attack", (double) 0);
		WISDOMMAXHEALTH = BUILDER.define("Wisdom Max Health", (double) 0);
		WISDOMMAXSPEED = BUILDER.define("Wisdom Max Speed", (double) 0);
		BUILDER.pop();
		BUILDER.push("Hamon Root: Defender");
		DEFENDERENABLED = BUILDER.define("Defender Enabled", true);
		DEFENDERMAXATK = BUILDER.define("Defender Max Attack", (double) 0);
		DEFENDERMAXHEALTH = BUILDER.define("Defender Max Health", (double) 0);
		DEFENDERMAXSPEED = BUILDER.define("Defender Max Speed", (double) 0);
		BUILDER.pop();
		BUILDER.push("Hamon Root: Envious");
		ENVIOUSENABLED = BUILDER.define("Envious Enabled", true);
		ENVIOUSMAXATK = BUILDER.define("Envious Max Attack", (double) 0);
		ENVIOUSMAXHEALTH = BUILDER.define("Envious Max Health", (double) 0);
		ENVIOUSMAXSPEED = BUILDER.define("Envious Max Speed", (double) 0);
		BUILDER.pop();
		BUILDER.push("Hamon Root: Trickster");
		TRICKSTERENABLED = BUILDER.define("Trickster Enabled", false);
		TRICKSTERMAXATK = BUILDER.define("Trickster Max Attack", (double) 0);
		TRICKSTERMAXHEALTH = BUILDER.define("Trickster Max Health", (double) 0);
		TRICKSTERMAXSPEED = BUILDER.define("Trickster Max Speed", (double) 0);
		BUILDER.pop();
		BUILDER.push("Hamon Root: Bubbly");
		BUBBLYENABLED = BUILDER.define("Bubbly Enabled", false);
		BUBBLYMAXATK = BUILDER.define("Bubbly Max Attack", (double) 0);
		BUBBLYMAXHEALTH = BUILDER.define("Bubbly Max Health", (double) 0);
		BUBBLYMAXSPEED = BUILDER.define("Bubbly Max Speed", (double) 0);
		BUILDER.pop();
		BUILDER.push("Hamon Root: Stylish");
		STYLISHENABLED = BUILDER.define("Stylish Enabled", false);
		STYLISHMAXATK = BUILDER.define("Stylish Max Attack", (double) 0);
		STYLISHMAXHEALTH = BUILDER.define("Stylish Max Health", (double) 0);
		STYLISHMAXSPEED = BUILDER.define("Stylish Max Speed", (double) 0);
		BUILDER.pop();

		SPEC = BUILDER.build();
	}

}
